---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
         - name: JAVA_OPTIONS
           value: "-Xmx512m -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true"
